import carRoute from "./car-route.json" with { type: "json" };

export const config = {
  demo: true,
  title: "서준 · 지우, 결혼합니다",
  description:
    "제주의 푸른 날에 평생을 함께하기로 했습니다. 소중한 분들께 결혼 소식을 전합니다.",
  date: "2026-11-15T12:00:00+09:00",
  siteUrl: "https://jonghoham.github.io/wedding/",
  kakaoJsKey: "38a8993d018421477735f7a0380d0ca1",
  musicUrl: "",
  hero: "./images/hero.jpg",
  shareImage: "./images/hero.jpg",
  groom: {
    name: "김서준",
    short: "서준",
    english: "Seojun",
    father: "김정호",
    mother: "박미경",
    phone: "",
    fatherPhone: "",
    motherPhone: "",
  },
  bride: {
    name: "이지우",
    short: "지우",
    english: "Jiwoo",
    father: "이영수",
    mother: "최은정",
    phone: "",
    fatherPhone: "",
    motherPhone: "",
  },
  message: [
    "함께 걷는 길 위에",
    "서로의 가장 다정한 계절이 되었습니다.",
    "",
    "제주의 바람이 시원한 날,",
    "저희 두 사람이 부부로 첫걸음을 내딛습니다.",
    "",
    "지금까지 곁에서 보내주신 사랑에 감사드리며",
    "소중한 당신을 저희의 시작에 초대합니다.",
  ],
  venue: {
    name: "중문컨벤션웨딩홀",
    detail: "ICC JEJU · 5층 오션뷰 홀",
    address: "제주특별자치도 서귀포시 중문관광로 224",
    lat: 33.2413,
    lng: 126.4243,
    verified: false,
    parking:
      "1·2층 실내주차장을 이용하실 수 있습니다. 일반요금은 입차 후 1시간 무료, 이후 30분당 1,000원(1일 최대 5,000원)입니다. 예식 하객 할인·무료 주차 적용은 별도 확인 중입니다.",
    phone: "064-738-6400",
  },
  gallery: [
    { src: "./images/hero.jpg", alt: "함께한 웨딩의 순간 · 샘플 사진" },
    { src: "./images/moment-1.jpg", alt: "웨딩의 따뜻한 기억 · 샘플 사진" },
    { src: "./images/moment-2.jpg", alt: "서로를 향한 약속 · 샘플 사진" },
    { src: "./images/moment-3.jpg", alt: "꽃과 함께한 하루 · 샘플 사진" },
    { src: "./images/moment-4.jpg", alt: "설렘이 머무는 장면 · 샘플 사진" },
    ...Array.from({ length: 15 }, (_, index) => ({
      src: `./images/moment-${index + 5}.jpg`,
      alt: `웨딩과 꽃의 순간 ${index + 6} · 샘플 사진`,
    })),
  ],
  accounts: [
    { side: "groom", role: "신랑", name: "김서준", bank: "", number: "" },
    { side: "groom", role: "아버지", name: "김정호", bank: "", number: "" },
    { side: "groom", role: "어머니", name: "박미경", bank: "", number: "" },
    { side: "bride", role: "신부", name: "이지우", bank: "", number: "" },
    { side: "bride", role: "아버지", name: "이영수", bank: "", number: "" },
    { side: "bride", role: "어머니", name: "최은정", bank: "", number: "" },
  ],
  routes: [
    {
      id: "car",
      mode: "car",
      name: "공항에서 자가용",
      color: "#387467",
      minutes: [70, 90],
      verified: false,
      ...carRoute,
      stops: [],
    },
    {
      id: "bus600",
      mode: "bus",
      name: "600번 공항리무진",
      color: "#b65b73",
      minutes: [90, 120],
      verified: false,
      steps: [
        "제주국제공항 1층 GATE 5 · 탑승",
        "한라병원 → 동광환승정류소",
        "중문관광단지 호텔 경유",
        "제주국제컨벤션센터/중문대포해안주상절리대 · 하차",
      ],
      roads: ["공항 → 중문관광단지 → ICC JEJU"],
      points: [
        [33.5066, 126.493],
        [33.489, 126.479],
        [33.452, 126.45],
        [33.41, 126.393],
        [33.368, 126.349],
        [33.309, 126.362],
        [33.265, 126.397],
        [33.25, 126.411],
        [33.2413, 126.4243],
      ],
      stops: [
        { name: "GATE 5 탑승 · 지도 위치는 예시", lat: 33.5066, lng: 126.493 },
        { name: "ICC 하차 · 지도 위치는 예시", lat: 33.2413, lng: 126.4243 },
      ],
      timetable: "",
    },
    {
      id: "bus601",
      mode: "bus",
      name: "601번 공항리무진",
      color: "#527baa",
      minutes: [90, 120],
      verified: false,
      steps: [
        "제주국제공항 1층 GATE 5 · 탑승",
        "한라병원 → 동광환승정류소",
        "중문관광단지 호텔 경유",
        "제주국제컨벤션센터/중문대포해안주상절리대 · 하차",
      ],
      roads: ["공항 → 중문관광단지 → ICC JEJU"],
      points: [
        [33.5066, 126.493],
        [33.489, 126.479],
        [33.452, 126.45],
        [33.41, 126.393],
        [33.368, 126.349],
        [33.309, 126.362],
        [33.265, 126.397],
        [33.25, 126.411],
        [33.2413, 126.4243],
      ],
      stops: [
        { name: "GATE 5 탑승 · 지도 위치는 예시", lat: 33.5066, lng: 126.493 },
        { name: "ICC 하차 · 지도 위치는 예시", lat: 33.2413, lng: 126.4243 },
      ],
      timetable: "",
    },
  ],
};
